# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 15:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('preview', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 9, 15, 15, 31, 30, 6957, tzinfo=utc))),
                ('image', models.ImageField(upload_to=main.models.upload_image_path_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 9, 15, 15, 31, 30, 22582, tzinfo=utc))),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 9, 15, 15, 31, 30, 6957, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Critic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 9, 15, 15, 31, 30, 22582, tzinfo=utc))),
                ('is_approved', models.BooleanField(default=False)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Act')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='critic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Critic'),
        ),
        migrations.AddField(
            model_name='act',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Community'),
        ),
    ]
