# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 18:36
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170915_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='act',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 18, 18, 36, 14, 922000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='act',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='act',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_image_path_handler),
        ),
        migrations.AlterField(
            model_name='act',
            name='preview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 18, 18, 36, 14, 924000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 18, 18, 36, 14, 922000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='critic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 18, 18, 36, 14, 923000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='critic',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
