# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171018_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 39, 31, 325000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 39, 31, 327000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 39, 31, 324000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='critic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 12, 39, 31, 326000, tzinfo=utc)),
        ),
    ]
