# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171020_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 14, 7, 2, 818000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 14, 7, 2, 820000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 14, 7, 2, 817000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='critic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 14, 7, 2, 819000, tzinfo=utc)),
        ),
    ]
