# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171020_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 12, 29, 6, 662000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 12, 29, 6, 664000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 12, 29, 6, 662000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='critic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 12, 29, 6, 663000, tzinfo=utc)),
        ),
    ]
