# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 12:32
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171030_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 12, 32, 42, 744000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='act',
            name='preview',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 12, 32, 42, 745000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='community',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 12, 32, 42, 743000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='critic',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 12, 32, 42, 744000, tzinfo=utc)),
        ),
    ]
